### ISSUE TITLE
Add Edit Task

### ISSUE THREAD

**Issue by Jvondamm** [Angop/ToDoApp#8]
This would require updating the visual the user sees as well as the database to reflect the updated information, and an edit button for the task. 

Time estimate: 5 hours

**Comment by Jvondamm** [comment]
Actual time: 1 hour

**Comment by Jvondamm** [comment]
Want either a popup or a new page, where we enter form and submit to update current task.

**Comment by Angop** [comment]
Completed edit task.
Josh time spent: 2 hours
Angela time spent: 8 hours
